#!/bin/sh

sudo pacman -Sy \
     feh vim zsh i3-gaps i3lock i3status dmenu ttf-roboto \
     adobe-source-code-pro-fonts xorg xorg-init git openssh rofi alacaritty \
     emacs noto-fonts tex-gyre-fonts zip unzip wpa_supplicant

# Create .config folder if it does not exist
mkdir -p $HOME/.config

# Create folder wallpapers if it does not exist
mkdir -p $HOME/wallpapers

# Install and enable norwegian osx keyboard layout
sudo cp keyboard/no /usr/share/X11/xkb/symbols/no

# Install i3 config
mkdir -p $HOME/.config/i3
ln -sf $(pwd)/config/i3/config $HOME/.config/i3/config

# Install rofi config
mkdir -p $HOME/.config/rofi
ln -sf $(pwd)/config/rofi/config.rasi $HOME/.config/rofi/config.rasi

# Install alacritty config
mkdir -p $HOME/.config/alacritty
ln -sf $(pwd)/config/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml

# Install xresource settings
ln -sf $(pwd)/Xresources $HOME/.Xresources

# Install xinitrc settings
ln -sf $(pwd)/xinitrc $HOME/.xinitrc

# Install emacs settings
ln -sf $(pwd)/spacemacs $HOME/.spacemacs

# Install git settings
ln -sf $(pwd)/gitconfig $HOME/.gitconfig

# Install zsh settings
ln -sf $(pwd)/zshrc $HOME/.zshrc

# Install tmux settings
ln -sf $(pwd)/tmux.conf $HOME/.tmux.conf

# Install font settings
sudo ln -sf $(pwd)/fonts/local.conf /etc/fonts/local.conf

if [ ! -d $HOME/.sdkman ]; then
  curl -s "https://get.sdkman.io" | bash
fi

if [ ! -d $HOME/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ ! -d $HOME/.emacs.d ]; then
  git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

